spring:
  profiles:
    active: local
    include: oauth

  datasource:
    url: jdbc:mysql://localhost:3306/booking?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rlaehdeod!23
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE